name: Build

on:
  workflow_run:
    workflows: ["Publish Build Agent Docker Image"]
    branches: [main]
    types: [completed]
  push:
    paths:
      - '!Dockerfile.build-agent'
      - '!.dockerignore'
      - '!.github/workflows/publish-build-agent.yml'
    branches: [ main ]
  pull_request:
    paths:
      - '!Dockerfile.build-agent'
      - '!.dockerignore'
      - '!.github/workflows/publish-build-agent.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    container:
      image: ghcr.io/wonderbird/rtb-build-agent:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    steps:
      - uses: actions/checkout@v2
          
      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Check
        run: make check
