name: Publish Build Agent Docker Image

on:
  schedule:
    # Every Friday at 21:00
    - cron: 0 21 * * 5
  push:
    paths:
      - 'Dockerfile.build-agent'
      - '.dockerignore'
    branches: [ main ]
  pull_request:
    paths:
      - 'Dockerfile.build-agent'
      - '.dockerignore'
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/wonderbird/rtb-build-agent
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}